### ISSUE TITLE
Wrong link to your blog

### ISSUE THREAD

**Issue by ashley** [nyu-ossd-s19/DaKoala-weekly#1]
You have the wrong long for your blog on the class's wiki. It should be https://nyu-ossd-s19.github.io/DaKoala-weekly/

**Comment by joannakl** [comment]
Is this issue still open? @DaKoala  it is up to you to resolve it and close it or to decide that it is not an issue.

**Comment by DaKoala** [comment]
Thanks for your kindly reminding. I have fixed the link on the course wiki page.
